[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name   http
    Listen 0.0.0.0
    Port   9880

[FILTER]
    Name   lua
    Match  *
    Script /fluent-bit/etc/cef.lua
    Call   to_cef
