@INCLUDE common.conf

[OUTPUT]
    Name   stdout
    Match  *
    Format json_lines

[OUTPUT]
    Name                  syslog
    Match                 *
    Host                  ${SIEM_HOST}
    Port                  ${SIEM_PORT}
    Mode                  ${SIEM_MODE}
    Syslog_Format         rfc5424
    Syslog_Message_Key    log
    Syslog_Appname_Preset netaudit
    Syslog_Severity_Preset 6
